# Generated by Django 4.2.2 on 2023-09-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=35)),
                ('upass', models.CharField(max_length=12)),
                ('ugender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEmale')], default='male', max_length=8)),
            ],
        ),
    ]
