# Generated by Django 4.2.2 on 2023-10-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpHotelApp', '0006_alter_corporate_cid_alter_hotel_hdesc'),
        ('megaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hname', models.CharField(default=' ', max_length=15)),
                ('hdesc', models.CharField(default=' ', max_length=100000)),
                ('hrooms', models.IntegerField(default=0)),
                ('hfacl', models.CharField(default=' ', max_length=100)),
                ('hrate', models.IntegerField(default=0)),
                ('hprice', models.IntegerField(default=0)),
                ('hdisc', models.IntegerField(default=0)),
                ('img_url', models.ImageField(default=' ', upload_to='images/')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpHotelApp.hotel')),
            ],
        ),
    ]
