# Generated by Django 4.2.2 on 2023-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megaApp', '0003_rename_cid_product_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uemail',
            field=models.CharField(default='noemail', max_length=15),
        ),
    ]
