# Generated by Django 4.2.2 on 2023-09-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpHotelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('hid', models.BigIntegerField(max_length=10, primary_key=True, serialize=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpHotelApp.corporate')),
            ],
        ),
    ]
