# Generated by Django 4.2.2 on 2023-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpHotelApp', '0003_hotel_hdesc_hotel_hdisc_hotel_hfacl_hotel_hname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hdisc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hrooms',
            field=models.IntegerField(default=0),
        ),
    ]
