# Generated by Django 4.2.2 on 2023-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpHotelApp', '0005_hotel_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='cid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hdesc',
            field=models.CharField(default=' ', max_length=100000),
        ),
    ]
